config/routes.rb
Eegm::Application.routes.draw do

  resources :items

  resources :purchase_orders

  resources :phones

  resources :suppliers

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'contacts', to: 'purchase_orders#contacts', as: 'gcontacts'

  root 'purchase_orders#index'

end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :supplier
  has_many :item_orders

  def supplier_name
  	supplier.try :name
  end

  def supplier_name=(name)
  	self.supplier = Supplier.find_or_create_by_name(name) if name.present?
  end

  def add_phone(phone)
    supplier.phones << phone
  end

  def date
  	created_at.to_s(:time)
  end

end

app/controllers/purchase_orders_controller.rb
require 'open-uri'
require 'nokogiri'

class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index

    @purchase_orders = PurchaseOrder.all

    @user = request.env['omniauth.auth']  if request.env['omniauth.auth']
  end

  def contacts
    if current_user
      #@google_contacts_user = GoogleContactsApi::User.new(current_user.token)
      #@contacts = @google_contacts_user.contacts

        gcontacts = "https://www.google.com/m8/feeds/contacts/default/full?max-results=1000&v=3.0&access_token=#{current_user.token}"
        @raw = Nokogiri::Slop(open(gcontacts))
        @contacts = @raw.html.body.feed.entry
    end
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @purchase_order }
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1
  # PATCH/PUT /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order.destroy
    respond_to do |format|
      format.html { redirect_to purchase_orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:supplier_id, :contact_person, :supplier_name)
    end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/purchase_orders/_form.html.erb
<%=javascript_tag do %>

$(document).ready(function(){
  $('#purchase_order_supplier_name').autocomplete({
    source: $('#purchase_order_supplier_name').data('autocomplete-source'),
    minLength: 2
  });
});
<% end %>


<%= form_for(@purchase_order) do |f| %>
  <% if @purchase_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
      <% @purchase_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :supplier_name %><br>
    <%= f.text_field :supplier_name, data: {autocomplete_source: suppliers_path} %>
  </div>

  <div class="field">
    <%= f.label :contact_person %><br>
    <%= f.text_field :contact_person %><br>
  </div>

  <div class="field">
    <div class="phones">
      <div class="phone_entry">
        <%= label_tag :phone, "Phone 1" %><br>
        <%= text_field_tag :phone, "", name: "phone[1]" %><br>
      </div>
    </div>
  <%= label_tag(:add_phone, "Add Phone", id: "add_phone")%>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchase_orders/contacts.html.erb
<h1> Google Contacts </h1>

<%@contacts.each do | c |  %>
  <%=c.title.text%></br>
<% end if @contacts%>

app/views/purchase_orders/edit.html.erb
<h1>Editing purchase_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase_order %> |
<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/index.html.erb
<h1>Listing Purchase Orders</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Supplier</th>
      <th>Contact Person</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_orders.each do |purchase_order| %>
      <tr>
        <td><%= purchase_order.date %><td>
        <td><%= purchase_order.supplier.name %></td>
        <td><%= purchase_order.contact_person %></td>
        <td><%= link_to 'Show', purchase_order %></td>
        <td><%= link_to 'Edit', edit_purchase_order_path(purchase_order) %></td>
        <td><%= link_to 'Destroy', purchase_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase order', new_purchase_order_path %>

app/views/purchase_orders/new.html.erb
<h1>New Purchase Order</h1>

<%= render 'form' %>

<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date Time:</strong>
  <%= @purchase_order.created_at.to_s(:time) %>
</p>


<p>
  <strong>Supplier:</strong>
  <%= @purchase_order.supplier.name %>
</p>

<p>
  <strong>Contact Person:</strong>
  <%= @purchase_order.contact_person %>
</p>

<%= link_to 'Edit', edit_purchase_order_path(@purchase_order) %> |
<%= link_to 'Back', purchase_orders_path %>